# Generated by Django 3.2 on 2022-05-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='essential',
            new_name='plans',
        ),
    ]
