# Generated by Django 3.2 on 2022-05-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_alter_plans_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting', models.IntegerField()),
                ('news', models.CharField(max_length=150)),
                ('reply', models.IntegerField()),
            ],
        ),
    ]
