# Generated by Django 3.2 on 2022-05-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='reply',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='waiting',
            field=models.IntegerField(default=1),
        ),
    ]
