# Generated by Django 3.2 on 2022-06-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0009_auto_20220604_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
