# Generated by Django 3.2 on 2022-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0011_ticket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
