# Generated by Django 3.2 on 2022-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0013_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='addon',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
