# Generated by Django 3.2 on 2022-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0015_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
