# Generated by Django 3.2 on 2022-06-06 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0021_alter_tickets_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.date)),
            ],
        ),
    ]
