# Generated by Django 3.2 on 2022-06-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0022_addon_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 6, 6)),
        ),
        migrations.AlterField(
            model_name='service',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 6, 6)),
        ),
    ]
