# Generated by Django 3.2 on 2022-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0023_auto_20220606_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
