# Generated by Django 3.2 on 2022-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0024_auto_20220606_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
