# Generated by Django 3.2 on 2022-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0027_alter_service_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
