# Generated by Django 3.2 on 2022-06-06 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0028_auto_20220606_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='next_duedate',
            field=models.DateField(default=datetime.date(2022, 7, 2)),
        ),
    ]
