# Generated by Django 3.2 on 2022-06-06 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0029_service_next_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='next_duedate',
            field=models.DateField(default=datetime.date(2022, 7, 4)),
        ),
    ]
